from PySide6.QtWidgets import QApplication, QDialog, QMainWindow, QMessageBox, QStyleFactory
from PySide6.QtCore import QThread, Slot, QSize
import sys

from ui_mega_v2_6 import Ui_MainWindow


class MainWindow(QMainWindow, Ui_MainWindow, QThread):
    def __init__(self, parent=None):
        super().__init__(parent)
        self.setupUi(self)
        self.init_show()
        self.init_hidden()
        self.custom_signal_slot()

    def custom_signal_slot(self):
        self.as_path_en.toggled.connect(self.srs_unchecked)
        self.srs_path_en.toggled.connect(self.as_unchecked)
        self.run_button.clicked.connect(self.run)
        self.therm_charge_dis_button.clicked.connect(self.therm_charge_dis)
        self.stop_button.clicked.connect(self.stop)
        self.equipments_comboBox.currentTextChanged.connect(self.equipment_show)
        self.tx_port_comboBox.currentTextChanged.connect(self.tx_port_show)
        self.tx_port_endc_lte_comboBox.currentTextChanged.connect(self.tx_port_endc_lte_show)
        self.rx_endc_desense_ns.stateChanged.connect(self.tx_port_endc_lte_state)
        self.equipments_comboBox.textActivated.connect(self.showout_en)

    def init_show(self):
        print(f'Equipment: {self.equipments_comboBox.currentText()}')
        print(f'Tx port: {self.tx_port_comboBox.currentText()}')

    def init_hidden(self):
        match self.equipments_comboBox.currentText():
            case 'Cmw100':
                self.hsupa_tech.setHidden(True)
                self.hsdpa_tech.setHidden(True)
                self.hsupa_tech.setChecked(False)
                self.hsdpa_tech.setChecked(False)
            case 'Cmw100+Fsw':
                self.hsupa_tech.setHidden(True)
                self.hsdpa_tech.setHidden(True)
                self.hsupa_tech.setChecked(False)
                self.hsdpa_tech.setChecked(False)
            case 'Anritsu8820':
                self.hsupa_tech.setHidden(False)
                self.hsdpa_tech.setHidden(False)
            case 'Anritsu8821':
                self.nr_tech.setHidden(True)
                self.wcdma_tech.setHidden(True)
                self.gsm_tech.setHidden(True)
                self.ulca_lte_tech.setHidden(True)
                self.hsupa_tech.setHidden(True)
                self.hsdpa_tech.setHidden(True)
                self.nr_tech.setChecked(False)
                self.wcdma_tech.setChecked(False)
                self.gsm_tech.setChecked(False)
                self.ulca_lte_tech.setChecked(False)
                self.hsupa_tech.setChecked(False)
                self.hsdpa_tech.setChecked(False)

    def srs_unchecked(self, checked):
        # if self.as_path_en.isChecked():
        #     self.srs_path_en.setChecked(False)
        if checked:
            self.srs_path_en.setChecked(False)

    def as_unchecked(self, checked):
        # if self.srs_path_en.isChecked():
        #     self.as_path_en.setChecked(False)
        if checked:
            self.as_path_en.setChecked(False)

    def toolbox_index_set(self, state_dict):
        self.bands_toolBox.setCurrentIndex(state_dict['bands_toolBox_index'])
        self.sync_path_toolBox.setCurrentIndex(state_dict['sync_path_toolBox_index'])
        self.txrx_path_toolBox.setCurrentIndex(state_dict['txrx_path_toolBox_index'])
        self.tabWidget.setCurrentIndex((state_dict['tabWidget_index']))

    def gui_state_get(self, state_dict):
        state_dict['equipment'] = self.equipments_comboBox.currentText()
        state_dict['tx_port_table_en'] = self.port_table_en.isChecked()
        state_dict['tx_port'] = self.tx_port_comboBox.CurrentText()
        state_dict['tx_port_endc_lte'] = self.tx_port_endc_lte_comboBox.currentText()
        state_dict['volt_mipi_en'] = self.volt_mipi_en.isChecked()
        state_dict['get_temp_en'] = self.get_temp_en.isChecked()
        state_dict['fdc_en'] = self.fdc_en.isChecked()
        state_dict['fbrx_en'] = self.fbrx_en.isChecked()
        state_dict['mipi_read_en'] = self.mipi_read_en.isChecked()
        state_dict['test_items_toolbox_index'] = self.test_items_toolBox.currentIndex()
        state_dict['tx_lmh_ns'] = self.tx_lmh_ns.isChecked()
        state_dict['tx_level_sweep_ns'] = self.tx_level_sweep_ns.isChecked()
        state_dict['tx_freq_sweep_ns'] = self.tx_freq_sweep_ns.isChecked()
        state_dict['tx_1rb_sweep_ns'] = self.tx_1rb_sweep_ns.isChecked()
        state_dict['tx_fcc_power_ns'] = self.tx_fcc_power_ns.isChecked()
        state_dict['tx_ce_power_ns'] = self.tx_ce_power_ns.isChecked()
        state_dict['tx_harmonics_ns'] = self.tx_harmonics_ns.isChecked()
        state_dict['tx_cbe_ns'] = self.tx_cbe_ns.isChecked()
        state_dict['tx_ulca_lte_ns'] = self.tx_ulca_lte_ns.isChecked()
        state_dict['tx_ulca_lte_cbe_ns'] = self.tx_ulca_lte_cbe_ns.isChecked()
        state_dict['rx_normal_ns'] = self.rx_normal_ns.isChecked()
        state_dict['rx_quick_ns'] = self.rx_quick_ns.isChecked()
        state_dict['rx_endc_desense'] = self.rx_endc_desense_ns.isChecked()
        state_dict['tx_lmh_s'] = self.tx_lmh_s.isChecked()
        state_dict['rx_normal_s'] = self.rx_normal_s.isChecked()
        state_dict['rxs_sweep_s'] = self.rxs_sweep_s.isChecked()
        state_dict['cbe_margin'] = float(self.cbe_margin.text())
        state_dict['sync_path_toolBox_index'] = self.sync_path_toolBox.currentIndex()
        state_dict['sync_path'] = self.sync_path_comboBox.currentText()
        state_dict['as_path_en'] = self.as_path_en.isChecked()
        state_dict['as_path'] = self.as_path_comboBox.currentText()
        state_dict['srs_path_en'] = self.srs_path_en.isChecked()
        state_dict['srs_path'] = self.srs_path_comboBox.currentText()
        state_dict['tx_level'] = self.tx_level_spinBox.value()
        state_dict['pcl_lb_level'] = self.pcl_lb_level_combo.currentText()
        state_dict['pcl_mb_level'] = self.pcl_mb_level_combo.currentText()
        state_dict['sync_path_endc'] = self.sync_path_comboBox_endc.currentText()
        state_dict['as_path_en_endc'] = self.as_path_en_endc.isChecked()
        state_dict['as_path_endc'] = self.as_path_comboBox_endc.currentText()
        state_dict['tx_level_lte_endc'] = self.tx_level_lte_spinBox_endc.value()
        state_dict['tx_level_nr_endc'] = self.tx_level_nr_spinBox_endc.value()
        state_dict['level_sweep_start'] = self.level_sweep_start_spinBox.value()
        state_dict['level_sweep_stop'] = self.level_stop_spinBox.value()
        state_dict['freq_sweep_step'] = int(self.freq_sweep_step.text())
        state_dict['freq_sweep_start'] = int(self.freq_sweep_start.text())
        state_dict['freq_sweep_stop'] = int(self.freq_sweep_stop.text())
        state_dict['txrx_path_toolBox_index'] = self.txrx_path_toolBox.currentIndex()
        state_dict['tx1'] = self.tx1.isChecked()
        state_dict['tx2'] = self.tx2.isChecked()
        state_dict['mimo'] = self.ulmimo.isChecked()
        state_dict['rx0'] = self.rx0.isChecked()
        state_dict['rx1'] = self.rx1.isChecked()
        state_dict['rx2'] = self.rx2.isChecked()
        state_dict['rx3'] = self.rx3.isChecked()
        state_dict['rx0rx1'] = self.rx0_rx1.isChecked()
        state_dict['rx2rx3'] = self.rx2_rx3.isChecked()
        state_dict['rx_all_path'] = self.rx_all_path.isChecked()
        state_dict['ue_txmax'] = self.ue_txmax.isChecked()
        state_dict['ue_txlow'] = self.ue_txlow.isChecked()
        state_dict['nr_tech'] = self.nr_tech.isChecked()
        state_dict['lte_tech'] = self.lte_tech.isChecked()
        state_dict['wcdma_tech'] = self.wcdma_tech.isChecked()
        state_dict['gsm_tech'] = self.gsm_tech.isChecked()
        state_dict['ulca_lte_tech'] = self.ulca_lte_tech.isChecked()
        state_dict['hsupa_tech'] = self.hsupa_tech.isChecked()
        state_dict['hsdpa_tech'] = self.hsdpa_tech.isChecked()
        state_dict['lch'] = self.lch.isChecked()
        state_dict['mch'] = self.mch.isChecked()
        state_dict['hch'] = self.hch.isChecked()
        state_dict['tabWidget_index'] = self.tabWidget.currentIndex()
        state_dict['bands_toolBox_index'] = self.bands_toolBox.currentIndex()
        state_dict['n5_nr'] = self.n5_nr.isChecked()
        state_dict['n8_nr'] = self.n8_nr.isChecked()
        state_dict['n12_nr'] = self.n12_nr.isChecked()
        state_dict['n13_nr'] = self.n13_nr.isChecked()
        state_dict['n14_nr'] = self.n14_nr.isChecked()
        state_dict['n20_nr'] = self.n20_nr.isChecked()
        state_dict['n24_nr'] = self.n24_nr.isChecked()
        state_dict['n26_nr'] = self.n26_nr.isChecked()
        state_dict['n71_nr'] = self.n71_nr.isChecked()
        state_dict['n28_a_nr'] = self.n28_a_nr.isChecked()
        state_dict['n28_b_nr'] = self.n28_b_nr.isChecked()
        state_dict['n29_nr'] = self.n29_nr.isChecked()
        state_dict['n32_nr'] = self.n32_nr.isChecked()
        state_dict['n1_nr'] = self.n1_nr.isChecked()
        state_dict['n2_nr'] = self.n2_nr.isChecked()
        state_dict['n3_nr'] = self.n3_nr.isChecked()
        state_dict['n4_nr'] = self.n4_nr.isChecked()
        state_dict['n7_nr'] = self.n7_nr.isChecked()
        state_dict['n30_nr'] = self.n30_nr.isChecked()
        state_dict['n25_nr'] = self.n25_nr.isChecked()
        state_dict['n66_nr'] = self.n66_nr.isChecked()
        state_dict['n70_nr'] = self.n70_nr.isChecked()
        state_dict['n39_nr'] = self.n39_nr.isChecked()
        state_dict['n40_nr'] = self.n40_nr.isChecked()
        state_dict['n38_nr'] = self.n38_nr.isChecked()
        state_dict['n41_nr'] = self.n41_nr.isChecked()
        state_dict['n34_nr'] = self.n34_nr.isChecked()
        state_dict['n75_nr'] = self.n75_nr.isChecked()
        state_dict['n76_nr'] = self.n76_nr.isChecked()
        state_dict['n255_nr'] = self.n255_nr.isChecked()
        state_dict['n256_nr'] = self.n256_nr.isChecked()
        state_dict['n77_nr'] = self.n77_nr.isChecked()
        state_dict['n78_nr'] = self.n78_nr.isChecked()
        state_dict['n79_nr'] = self.n79_nr.isChecked()
        state_dict['b5_lte'] = self.b5_lte.isChecked()
        state_dict['b8_lte'] = self.b8_lte.isChecked()
        state_dict['b12_lte'] = self.b12_lte.isChecked()
        state_dict['b13_lte'] = self.b13_lte.isChecked()
        state_dict['b14_lte'] = self.b14_lte.isChecked()
        state_dict['b17_lte'] = self.b17_lte.isChecked()
        state_dict['b18_lte'] = self.b18_lte.isChecked()
        state_dict['b19_lte'] = self.b19_lte.isChecked()
        state_dict['b20_lte'] = self.b20_lte.isChecked()
        state_dict['b26_lte'] = self.b26_lte.isChecked()
        state_dict['b28_a_lte'] = self.b28_a_lte.isChecked()
        state_dict['b28_b_lte'] = self.b28_b_lte.isChecked()
        state_dict['b29_lte'] = self.b29_lte.isChecked()
        state_dict['b32_lte'] = self.b32_lte.isChecked()
        state_dict['b71_lte'] = self.b71_lte.isChecked()
        state_dict['b24_lte'] = self.b24_lte.isChecked()
        state_dict['b1_lte'] = self.b1_lte.isChecked()
        state_dict['b2_lte'] = self.b2_lte.isChecked()
        state_dict['b3_lte'] = self.b3_lte.isChecked()
        state_dict['b4_lte'] = self.b4_lte.isChecked()
        state_dict['b7_lte'] = self.b7_lte.isChecked()
        state_dict['b30_lte'] = self.b30_lte.isChecked()
        state_dict['b25_lte'] = self.b25_lte.isChecked()
        state_dict['b66_lte'] = self.b66_lte.isChecked()
        state_dict['b21_lte'] = self.b21_lte.isChecked()
        state_dict['b39_lte'] = self.b39_lte.isChecked()
        state_dict['b40_lte'] = self.b40_lte.isChecked()
        state_dict['b38_lte'] = self.b38_lte.isChecked()
        state_dict['b41_lte'] = self.b41_lte.isChecked()
        state_dict['b23_lte'] = self.b23_lte.isChecked()
        state_dict['b42_lte'] = self.b42_lte.isChecked()
        state_dict['b48_lte'] = self.b48_lte.isChecked()
        state_dict['b5_wcdma'] = self.b5_wcdma.isChecked()
        state_dict['b8_wcdma'] = self.b8_wcdma.isChecked()
        state_dict['b6_wcdma'] = self.b6_wcdma.isChecked()
        state_dict['b19_wcdma'] = self.b19_wcdma.isChecked()
        state_dict['b1_wcdma'] = self.b1_wcdma.isChecked()
        state_dict['b2_wcdma'] = self.b2_wcdma.isChecked()
        state_dict['b4_wcdma'] = self.b4_wcdma.isChecked()
        state_dict['gsm850'] = self.gsm850.isChecked()
        state_dict['gsm900'] = self.gsm850.isChecked()
        state_dict['gsm1800'] = self.gsm1800.isChecked()
        state_dict['gsm1900'] = self.gsm1900.isChecked()
        state_dict['bw1p4_lte'] = self.bw1p4_lte.isChecked()
        state_dict['bw3_lte'] = self.bw1p4_lte.isChecked()
        state_dict['bw5_lte'] = self.bw1p4_lte.isChecked()
        state_dict['bw10_lte'] = self.bw1p4_lte.isChecked()
        state_dict['bw15_lte'] = self.bw1p4_lte.isChecked()
        state_dict['bw20_lte'] = self.bw1p4_lte.isChecked()
        state_dict['bw5_nr'] = self.bw5_nr.isChecked()
        state_dict['bw10_nr'] = self.bw10_nr.isChecked()
        state_dict['bw15_nr'] = self.bw15_nr.isChecked()
        state_dict['bw20_nr'] = self.bw20_nr.isChecked()
        state_dict['bw25_nr'] = self.bw25_nr.isChecked()
        state_dict['bw30_nr'] = self.bw30_nr.isChecked()
        state_dict['bw40_nr'] = self.bw40_nr.isChecked()
        state_dict['bw50_nr'] = self.bw50_nr.isChecked()
        state_dict['bw60_nr'] = self.bw60_nr.isChecked()
        state_dict['bw80_nr'] = self.bw80_nr.isChecked()
        state_dict['bw90_nr'] = self.bw90_nr.isChecked()
        state_dict['bw100_nr'] = self.bw100_nr.isChecked()
        state_dict['bw70_nr'] = self.bw70_nr.isChecked()
        state_dict['bw35_nr'] = self.bw35_nr.isChecked()
        state_dict['bw45_nr'] = self.bw45_nr.isChecked()
        state_dict['bw20_5'] = self.bw20_5.isChecked()
        state_dict['bw5_20'] = self.bw5_20.isChecked()
        state_dict['bw20_10'] = self.bw20_10.isChecked()
        state_dict['bw10_20'] = self.bw10_20.isChecked()
        state_dict['bw20_15'] = self.bw20_15.isChecked()
        state_dict['bw15_20'] = self.bw15_20.isChecked()
        state_dict['bw20_20'] = self.bw20_20.isChecked()
        state_dict['bw15_15'] = self.bw15_15.isChecked()
        state_dict['bw15_10'] = self.bw15_10.isChecked()
        state_dict['bw10_15'] = self.bw10_15.isChecked()
        state_dict['bw5_10'] = self.bw5_10.isChecked()
        state_dict['bw10_5'] = self.bw10_5.isChecked()
        state_dict['bw10_10'] = self.bw10_10.isChecked()
        state_dict['bw5_15'] = self.bw5_15.isChecked()
        state_dict['bw15_5'] = self.bw15_5.isChecked()
        state_dict['bw40'] = self.bw40.isChecked()
        state_dict['qpsk_lte'] = self.qpsk_lte.isChecked()
        state_dict['q16_lte'] = self.q16_lte.isChecked()
        state_dict['q64_lte'] = self.q64_lte.isChecked()
        state_dict['q256_lte'] = self.q256_lte.isChecked()
        state_dict['qpsk_nr'] = self.qpsk_nr.isChecked()
        state_dict['q16_nr'] = self.q16_nr.isChecked()
        state_dict['q64_nr'] = self.q64_nr.isChecked()
        state_dict['q256_nr'] = self.q256_nr.isChecked()
        state_dict['bpsk_nr'] = self.bpsk_nr.isChecked()
        state_dict['dfts_nr'] = self.dfts_nr.isChecked()
        state_dict['cp_nr'] = self.cp_nr.isChecked()
        state_dict['prb0_lte'] = self.prb0_lte.isChecked()
        state_dict['prbmax_lte'] = self.prbmax_lte.isChecked()
        state_dict['frb_lte'] = self.frb_lte.isChecked()
        state_dict['one_rb_0_lte'] = self.one_rb_0_lte.isChecked()
        state_dict['one_rb_max_lte'] = self.one_rb_max_lte.isChecked()
        state_dict['inner_full_nr'] = self.inner_full_nr.isChecked()
        state_dict['outer_full_nr'] = self.outer_full_nr.isChecked()
        state_dict['inner_1rb_left_nr'] = self.inner_1rb_left_nr.isChecked()
        state_dict['inner_1rb_right_nr'] = self.inner_1rb_right_nr.isChecked()
        state_dict['edge_1rb_left_nr'] = self.edge_1rb_left_nr.isChecked()
        state_dict['edge_1rb_right_nr'] = self.edge_1rb_right_nr.isChecked()
        state_dict['edge_full_left_nr'] = self.edge_full_left_nr.isChecked()
        state_dict['edge_full_right_nr'] = self.edge_full_right_nr.isChecked()
        state_dict['tmpchmb_en'] = self.tmpchmb_en.isChecked()
        state_dict['hthv_en'] = self.hthv_en.isChecked()
        state_dict['htlv_en'] = self.htlv_en.isChecked()
        state_dict['ntnv_en'] = self.ntnv_en.isChecked()
        state_dict['lthv_en'] = self.lthv_en.isChecked()
        state_dict['ltlv_en'] = self.ltlv_en.isChecked()
        state_dict['psu_en'] = self.psu_en.isChecked()
        state_dict['hv_en'] = self.hv_en.isChecked()
        state_dict['nv_en'] = self.nv_en.isChecked()
        state_dict['lv_en'] = self.lv_en.isChecked()
        state_dict['odpm2_en'] = self.odpm2_en.isChecked()
        state_dict['ht_value'] = self.ht_spinBox.value()
        state_dict['nt_value'] = self.nt_spinBox.value()
        state_dict['lt_value'] = self.lt_spinBox.value()
        state_dict['hv_value'] = self.hv_doubleSpinBox.value()
        state_dict['nv_value'] = self.nv_doubleSpinBox.value()
        state_dict['lv_value'] = self.lv_doubleSpinBox.value()
        state_dict['input_level_sig_anritsu'] = self.input_level_sig_anritsu_spinBox.value()
        state_dict['rfout_port_sig_anritsu'] = self.rfout_port_sig_anritsu_comboBox.value()

        return state_dict

    def gui_state_set(self, state_dict):
        self.tabWidget.setCurrentIndex(state_dict['tabWidget'])

        self.equipments_comboBox.setCurrentText(state_dict['equipment'])
        self.port_table_en.setChecked(state_dict['tx_port_table_en'])
        self.tx_port_comboBox.setCurrentText(state_dict['tx_port'])
        self.tx_port_endc_lte_comboBox.setcurrentText(state_dict['tx_port_endc_lte'])
        self.volt_mipi_en.setChecked(state_dict['volt_mipi_en'])
        self.get_temp_en.setChecked(state_dict['get_temp_en'])
        self.fdc_en.setChecked(state_dict['fdc_en'])
        self.fbrx_en.setChecked(state_dict['fbrx_en'])
        self.mipi_read_en.setChecked(state_dict['mipi_read_en'])
        self.test_items_toolBox.setCurrentIndex(state_dict['test_items_toolbox_index'])
        self.tx_lmh_ns.setChecked(state_dict['tx_lmh_ns'])
        self.tx_level_sweep_ns.setChecked(state_dict['tx_level_sweep_ns'])
        self.tx_freq_sweep_ns.setChecked(state_dict['tx_freq_sweep_ns'])
        self.tx_1rb_sweep_ns.setChecked(state_dict['tx_1rb_sweep_ns'])
        self.tx_fcc_power_ns.setChecked(state_dict['tx_fcc_power_ns'])
        self.tx_ce_power_ns.setChecked(state_dict['tx_ce_power_ns'])
        self.tx_harmonics_ns.setChecked(state_dict['tx_harmonics_ns'])
        self.tx_cbe_ns.setChecked(state_dict['tx_cbe_ns'])
        self.tx_ulca_lte_ns.setChecked(state_dict['tx_ulca_lte_ns'])
        self.tx_ulca_lte_cbe_ns.setChecked(state_dict['tx_ulca_lte_cbe_ns'])
        self.rx_normal_ns.setChecked(state_dict['rx_normal_ns'])
        self.rx_quick_ns.setChecked(state_dict['rx_quick_ns'])
        self.rx_endc_desense_ns.setChecked(state_dict['rx_endc_desense'])
        self.tx_lmh_s.setChecked(state_dict['tx_lmh_s'])
        self.rx_normal_s.setChecked(state_dict['rx_normal_s'])
        self.rxs_sweep_s.setChecked(state_dict['rxs_sweep_s'])
        self.cbe_margin.setText((state_dict['cbe_margin']))
        self.sync_path_toolBox.setCurrentIndex(state_dict['sync_path_toolBox_index'])
        self.sync_path_comboBox.setCurrentText(state_dict['sync_path'])
        self.as_path_en.setChecked(state_dict['as_path_en'])
        self.as_path_comboBox.setCurrentText(state_dict['as_path'])
        self.srs_path_en.setChecked(state_dict['srs_path_en'])
        self.srs_path_comboBox.setCurrentText(state_dict['srs_path'])
        self.tx_level_spinBox.setValue(state_dict['tx_level'])
        self.pcl_lb_level_combo.setCurrentText(state_dict['pcl_lb_level'])
        self.pcl_mb_level_combo.setCurrentText(state_dict['pcl_mb_level'])
        self.sync_path_comboBox_endc.setCurrentText(state_dict['sync_path_endc'])
        self.as_path_en_endc.setChecked(state_dict['as_path_en_endc'])
        self.as_path_comboBox_endc.setCurrentText(state_dict['as_path_endc'])
        self.tx_level_lte_spinBox_endc.setValue(state_dict['tx_level_lte_endc'])
        self.tx_level_nr_spinBox_endc.setValue(state_dict['tx_level_nr_endc'])
        self.level_sweep_start_spinBox.setValue(state_dict['level_sweep_start'])
        self.level_stop_spinBox.setValue(state_dict['level_sweep_stop'])
        self.freq_sweep_step.setText(str(state_dict['freq_sweep_step']))  # Convert to string
        self.freq_sweep_start.setText(str(state_dict['freq_sweep_start']))
        self.freq_sweep_stop.setText(str(state_dict['freq_sweep_stop']))
        self.txrx_path_toolBox.setCurrentIndex(state_dict['txrx_path_toolBox_index'])
        self.tx1.setChecked(state_dict['tx1'])
        self.tx2.setChecked(state_dict['tx2'])
        self.ulmimo.setChecked(state_dict['mimo'])
        self.rx0.setChecked(state_dict['rx0'])
        self.rx1.setChecked(state_dict['rx1'])
        self.rx2.setChecked(state_dict['rx2'])
        self.rx3.setChecked(state_dict['rx3'])
        self.rx0_rx1.setChecked(state_dict['rx0rx1'])
        self.rx2_rx3.setChecked(state_dict['rx2rx3'])
        self.rx_all_path.setChecked(state_dict['rx_all_path'])
        self.ue_txmax.setChecked(state_dict['ue_txmax'])
        self.ue_txlow.setChecked(state_dict['ue_txlow'])
        self.nr_tech.setChecked(state_dict['nr_tech'])
        self.lte_tech.setChecked(state_dict['lte_tech'])
        self.wcdma_tech.setChecked(state_dict['wcdma_tech'])
        self.gsm_tech.setChecked(state_dict['gsm_tech'])
        self.ulca_lte_tech.setChecked(state_dict['ulca_lte_tech'])
        self.hsupa_tech.setChecked(state_dict['hsupa_tech'])
        self.hsdpa_tech.setChecked(state_dict['hsdpa_tech'])
        self.lch.setChecked(state_dict['lch'])
        self.mch.setChecked(state_dict['mch'])
        self.hch.setChecked(state_dict['hch'])
        self.tabWidget.setCurrentIndex(state_dict['tabWidget_index'])
        self.bands_toolBox.setCurrentIndex(state_dict['bands_toolBox_index'])
        self.n5_nr.setChecked(state_dict['n5_nr'])
        self.n8_nr.setChecked(state_dict['n8_nr'])
        self.n12_nr.setChecked(state_dict['n12_nr'])
        self.n13_nr.setChecked(state_dict['n13_nr'])
        self.n14_nr.setChecked(state_dict['n14_nr'])
        self.n20_nr.setChecked(state_dict['n20_nr'])
        self.n24_nr.setChecked(state_dict['n24_nr'])
        self.n26_nr.setChecked(state_dict['n26_nr'])
        self.n71_nr.setChecked(state_dict['n71_nr'])
        self.n28_a_nr.setChecked(state_dict['n28_a_nr'])
        self.n28_b_nr.setChecked(state_dict['n28_b_nr'])
        self.n29_nr.setChecked(state_dict['n29_nr'])
        self.n32_nr.setChecked(state_dict['n32_nr'])
        self.n1_nr.setChecked(state_dict['n1_nr'])
        self.n2_nr.setChecked(state_dict['n2_nr'])
        self.n3_nr.setChecked(state_dict['n3_nr'])
        self.n4_nr.setChecked(state_dict['n4_nr'])
        self.n7_nr.setChecked(state_dict['n7_nr'])
        self.n30_nr.setChecked(state_dict['n30_nr'])
        self.n25_nr.setChecked(state_dict['n25_nr'])
        self.n66_nr.setChecked(state_dict['n66_nr'])
        self.n70_nr.setChecked(state_dict['n70_nr'])
        self.n39_nr.setChecked(state_dict['n39_nr'])
        self.n40_nr.setChecked(state_dict['n40_nr'])
        self.n38_nr.setChecked(state_dict['n38_nr'])
        self.n41_nr.setChecked(state_dict['n41_nr'])
        self.n34_nr.setChecked(state_dict['n34_nr'])
        self.n75_nr.setChecked(state_dict['n75_nr'])
        self.n76_nr.setChecked(state_dict['n76_nr'])
        self.n255_nr.setChecked(state_dict['n255_nr'])
        self.n256_nr.setChecked(state_dict['n256_nr'])
        self.n77_nr.setChecked(state_dict['n77_nr'])
        self.n78_nr.setChecked(state_dict['n78_nr'])
        self.n79_nr.setChecked(state_dict['n79_nr'])
        self.b5_lte.setChecked(state_dict['b5_lte'])
        self.b8_lte.setChecked(state_dict['b8_lte'])
        self.b12_lte.setChecked(state_dict['b12_lte'])
        self.b13_lte.setChecked(state_dict['b13_lte'])
        self.b14_lte.setChecked(state_dict['b14_lte'])
        self.b17_lte.setChecked(state_dict['b17_lte'])
        self.b18_lte.setChecked(state_dict['b18_lte'])
        self.b19_lte.setChecked(state_dict['b19_lte'])
        self.b20_lte.setChecked(state_dict['b20_lte'])
        self.b26_lte.setChecked(state_dict['b26_lte'])
        self.b28_a_lte.setChecked(state_dict['b28_a_lte'])
        self.b28_b_lte.setChecked(state_dict['b28_b_lte'])
        self.b29_lte.setChecked(state_dict['b29_lte'])
        self.b32_lte.setChecked(state_dict['b32_lte'])
        self.b71_lte.setChecked(state_dict['b71_lte'])
        self.b24_lte.setChecked(state_dict['b24_lte'])
        self.b1_lte.setChecked(state_dict['b1_lte'])
        self.b2_lte.setChecked(state_dict['b2_lte'])
        self.b3_lte.setChecked(state_dict['b3_lte'])
        self.b4_lte.setChecked(state_dict['b4_lte'])
        self.b7_lte.setChecked(state_dict['b7_lte'])
        self.b30_lte.setChecked(state_dict['b30_lte'])
        self.b25_lte.setChecked(state_dict['b25_lte'])
        self.b66_lte.setChecked(state_dict['b66_lte'])
        self.b21_lte.setChecked(state_dict['b21_lte'])
        self.b39_lte.setChecked(state_dict['b39_lte'])
        self.b40_lte.setChecked(state_dict['b40_lte'])
        self.b38_lte.setChecked(state_dict['b38_lte'])
        self.b41_lte.setChecked(state_dict['b41_lte'])
        self.b23_lte.setChecked(state_dict['b23_lte'])
        self.b42_lte.setChecked(state_dict['b42_lte'])
        self.b48_lte.setChecked(state_dict['b48_lte'])
        self.b5_wcdma.setChecked(state_dict['b5_wcdma'])
        self.b8_wcdma.setChecked(state_dict['b8_wcdma'])
        self.b6_wcdma.setChecked(state_dict['b6_wcdma'])
        self.b19_wcdma.setChecked(state_dict['b19_wcdma'])
        self.b1_wcdma.setChecked(state_dict['b1_wcdma'])
        self.b2_wcdma.setChecked(state_dict['b2_wcdma'])
        self.b4_wcdma.setChecked(state_dict['b4_wcdma'])
        self.gsm850.setChecked(state_dict['gsm850'])
        self.gsm900.setChecked(state_dict['gsm900'])
        self.gsm1800.setChecked(state_dict['gsm1800'])
        self.gsm1900.setChecked(state_dict['gsm1900'])
        self.bw1p4_lte.setChecked(state_dict['bw1p4_lte'])
        self.bw3_lte.setChecked(state_dict['bw3_lte'])
        self.bw5_lte.setChecked(state_dict['bw5_lte'])
        self.bw10_lte.setChecked(state_dict['bw10_lte'])
        self.bw15_lte.setChecked(state_dict['bw15_lte'])
        self.bw20_lte.setChecked(state_dict['bw20_lte'])
        self.bw5_nr.setChecked(state_dict['bw5_nr'])
        self.bw10_nr.setChecked(state_dict['bw10_nr'])
        self.bw15_nr.setChecked(state_dict['bw15_nr'])
        self.bw20_nr.setChecked(state_dict['bw20_nr'])
        self.bw25_nr.setChecked(state_dict['bw25_nr'])
        self.bw30_nr.setChecked(state_dict['bw30_nr'])
        self.bw40_nr.setChecked(state_dict['bw40_nr'])
        self.bw50_nr.setChecked(state_dict['bw50_nr'])
        self.bw60_nr.setChecked(state_dict['bw60_nr'])
        self.bw80_nr.setChecked(state_dict['bw80_nr'])
        self.bw90_nr.setChecked(state_dict['bw90_nr'])
        self.bw100_nr.setChecked(state_dict['bw100_nr'])
        self.bw70_nr.setChecked(state_dict['bw70_nr'])
        self.bw35_nr.setChecked(state_dict['bw35_nr'])
        self.bw45_nr.setChecked(state_dict['bw45_nr'])
        self.bw20_5.setChecked(state_dict['bw20_5'])
        self.bw5_20.setChecked(state_dict['bw5_20'])
        self.bw20_10.setChecked(state_dict['bw20_10'])
        self.bw10_20.setChecked(state_dict['bw10_20'])
        self.bw20_15.setChecked(state_dict['bw20_15'])
        self.bw15_20.setChecked(state_dict['bw15_20'])
        self.bw20_20.setChecked(state_dict['bw20_20'])
        self.bw15_15.setChecked(state_dict['bw15_15'])
        self.bw15_10.setChecked(state_dict['bw15_10'])
        self.bw10_15.setChecked(state_dict['bw10_15'])
        self.bw5_10.setChecked(state_dict['bw5_10'])
        self.bw10_5.setChecked(state_dict['bw10_5'])
        self.bw10_10.setChecked(state_dict['bw10_10'])
        self.bw5_15.setChecked(state_dict['bw5_15'])
        self.bw15_5.setChecked(state_dict['bw15_5'])
        self.bw40.setChecked(state_dict['bw40'])
        self.qpsk_lte.setChecked(state_dict['qpsk_lte'])
        self.q16_lte.setChecked(state_dict['q16_lte'])
        self.q64_lte.setChecked(state_dict['q64_lte'])
        self.q256_lte.setChecked(state_dict['q256_lte'])
        self.qpsk_nr.setChecked(state_dict['qpsk_nr'])
        self.q16_nr.setChecked(state_dict['q16_nr'])
        self.q64_nr.setChecked(state_dict['q64_nr'])
        self.q256_nr.setChecked(state_dict['q256_nr'])
        self.bpsk_nr.setChecked(state_dict['bpsk_nr'])
        self.dfts_nr.setChecked(state_dict['dfts_nr'])
        self.cp_nr.setChecked(state_dict['cp_nr'])
        self.prb0_lte.setChecked(state_dict['prb0_lte'])
        self.prbmax_lte.setChecked(state_dict['prbmax_lte'])
        self.frb_lte.setChecked(state_dict['frb_lte'])
        self.one_rb_0_lte.setChecked(state_dict['one_rb_0_lte'])
        self.one_rb_max_lte.setChecked(state_dict['one_rb_max_lte'])
        self.inner_full_nr.setChecked(state_dict['inner_full_nr'])
        self.outer_full_nr.setChecked(state_dict['outer_full_nr'])
        self.inner_1rb_left_nr.setChecked(state_dict['inner_1rb_left_nr'])
        self.inner_1rb_right_nr.setChecked(state_dict['inner_1rb_right_nr'])
        self.edge_1rb_left_nr.setChecked(state_dict['edge_1rb_left_nr'])
        self.edge_1rb_right_nr.setChecked(state_dict['edge_1rb_right_nr'])
        self.edge_full_left_nr.setChecked(state_dict['edge_full_left_nr'])
        self.edge_full_right_nr.setChecked(state_dict['edge_full_right_nr'])
        self.tmpchmb_en.setChecked(state_dict['tmpchmb_en'])
        self.hthv_en.setChecked(state_dict['hthv_en'])
        self.htlv_en.setChecked(state_dict['htlv_en'])
        self.ntnv_en.setChecked(state_dict['ntnv_en'])
        self.lthv_en.setChecked(state_dict['lthv_en'])
        self.ltlv_en.setChecked(state_dict['ltlv_en'])
        self.psu_en.setChecked(state_dict['psu_en'])
        self.hv_en.setChecked(state_dict['hv_en'])
        self.nv_en.setChecked(state_dict['nv_en'])
        self.lv_en.setChecked(state_dict['lv_en'])
        self.odpm2_en.setChecked(state_dict['odpm2_en'])
        self.ht_spinBox.setValue(state_dict['ht_value'])
        self.nt_spinBox.setValue(state_dict['nt_value'])
        self.lt_spinBox.setValue(state_dict['lt_value'])
        self.hv_doubleSpinBox.setValue(state_dict['hv_value'])
        self.nv_doubleSpinBox.setValue(state_dict['nv_value'])
        self.lv_doubleSpinBox.setValue(state_dict['lv_value'])
        self.input_level_sig_anritsu_spinBox.setValue(state_dict['input_level_sig_anritsu'])
        self.rfout_port_sig_anritsu_comboBox.setValue(state_dict['rfout_port_sig_anritsu'])

    def tx_port_show(self):
        print(f'Tx Port: {self.tx_port_comboBox.currentText()}')

    def tx_port_endc_lte_show(self):
        print(f'Endc LTE Tx Port: {self.tx_port_endc_lte_comboBox.currentText()}')

    @staticmethod
    def tx_port_endc_lte_state(checked):
        if checked:
            print(f'Endc LTE port Enabled')
        else:
            print(f'Endc LTE port Disabled')

    def showout_en(self):
        match self.equipments_comboBox.currentText():
            case 'Cmw100':
                self.nr_tech.setHidden(False)
                self.wcdma_tech.setHidden(False)
                self.gsm_tech.setHidden(False)
                self.ulca_lte_tech.setHidden(False)
                self.hsupa_tech.setHidden(True)
                self.hsdpa_tech.setHidden(True)
                self.hsupa_tech.setChecked(False)
                self.hsdpa_tech.setChecked(False)
            case 'Cmw100+Fsw':
                self.nr_tech.setHidden(False)
                self.wcdma_tech.setHidden(False)
                self.gsm_tech.setHidden(False)
                self.ulca_lte_tech.setHidden(False)
                self.hsupa_tech.setHidden(True)
                self.hsdpa_tech.setHidden(True)
                self.hsupa_tech.setChecked(False)
                self.hsdpa_tech.setChecked(False)
            case 'Anritsu8820':
                self.nr_tech.setHidden(False)
                self.wcdma_tech.setHidden(False)
                self.gsm_tech.setHidden(False)
                self.ulca_lte_tech.setHidden(False)
                self.hsupa_tech.setHidden(False)
                self.hsdpa_tech.setHidden(False)
            case 'Anritsu8821':
                self.nr_tech.setHidden(True)
                self.wcdma_tech.setHidden(True)
                self.gsm_tech.setHidden(True)
                self.ulca_lte_tech.setHidden(True)
                self.hsupa_tech.setHidden(True)
                self.hsdpa_tech.setHidden(True)
                self.nr_tech.setChecked(False)
                self.wcdma_tech.setChecked(False)
                self.gsm_tech.setChecked(False)
                self.ulca_lte_tech.setChecked(False)
                self.hsupa_tech.setChecked(False)
                self.hsdpa_tech.setChecked(False)

    def equipment_show(self):
        print(f'Equipment: {self.equipments_comboBox.currentText()}')

    def run(self):
        print('run')

    def therm_charge_dis(self):
        print('therm dis')

    def stop(self):
        print('stop')


def main():
    app = QApplication(sys.argv)
    style = QStyleFactory.create('Fusion')
    app.setStyle(style)
    win = MainWindow()
    # win.setMaximumSize(QSize(1491, 776))
    win.show()
    sys.exit(app.exec())


if __name__ == "__main__":
    main()
